# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACDemo' do

   pod 'ReactiveCocoa','~>2.5'
   pod 'Masonry'
   pod 'AFNetworking'
   pod 'SDWebImage'
   pod 'MJExtension'
   pod 'UITableView+FDTemplateLayoutCell', '~>1.6'

end
